name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        id: runBuild
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deployment
        id: herokuDeployment
        if: ${{ (github.event_name == 'push') && !(contains(join(toJson(github.event.commits.*.message)),'#skip')) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-fso-app"
          heroku_email: ${{secrets.HEROKU_API_USER}}
          healthcheck: "https://pokedex-fso-app.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: ${{ (github.event_name == 'push') && !(contains(join(toJson(github.event.commits.*.message)),'#skip')) }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      #test
      - name: Check deployed URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pokedex-fso-app.herokuapp.com
          max-attempts: 2
          retry-delay: 5s
      # Slack logs
      - name: build failure
        if: failure() && steps.runBuild.outcome == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: 'failure'
          fields: repo,message,commit,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: deployment success
        if: always() && steps.herokuDeployment.outcome == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,repo,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `New version deployed to https://pokedex-fso-app.herokuapp.com (${process.env.AS_COMMIT}) of ${process.env.AS_REPO} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}